# News Scraper - Multi-Source (InfoMoney, MoneyTimes, Exame)

This notebook collects financial news from three sources via the WordPress REST API:
**InfoMoney**, **MoneyTimes**, and **Exame**.

It scrapes each source in parallel (one thread per search term), consolidates the results,
applies a 30-keyword thematic filter, and combines all sources into a single dataset
for downstream sentiment analysis.

In [12]:
import sys
import os
import glob
from datetime import datetime
import pandas as pd

# Fix para erro de Unicode no Windows
os.environ["PYTHONUTF8"] = "1"

# Auto-reload to reflect script changes
%load_ext autoreload
%autoreload 2

# Add root directory to path to import src modules
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from src.scraper import get_news_from_period
from src.utils.logger import setup_logger

# Configure logger to see output in the notebook
logger = setup_logger()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Parameter Definition
Define the list of search terms, the start date for collection, and the output folder.

In [13]:
SEARCH_TERMS = [
    "Ibovespa", "BOVA11", "Bolsa", "Ações", "Mercado", "Câmbio", "Dólar", "Juros", "Selic", "Inflação",
    "IPCA", "Banco Central", "Copom", "Fazenda", "CDI", "Petrobras", "Vale", "Itaú", "Bradesco", "Banco do Brasil",
    "B3", "Ambev", "Eletrobras", "WEG", "Suzano", "Gerdau", "Localiza", "Rumo", "Equatorial", "BTG Pactual", "Economia"
]

START_DATE = datetime(2025, 1, 1)
END_DATE   = datetime(2025, 12, 31)

# Date-based folder: scraper/YYYYMMDD/infomoney
RUN_DATE   = datetime.now().strftime("%Y%m%d")
OUTPUT_DIR = os.path.join("..", "data", "scraper", RUN_DATE, "infomoney")
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"Run date    : {RUN_DATE}")
print(f"Search terms: {len(SEARCH_TERMS)}")
print(f"Period      : {START_DATE.date()} → {END_DATE.date()}")
print(f"Output dir  : {os.path.abspath(OUTPUT_DIR)}")

Run date    : 20260408
Search terms: 31
Period      : 2025-01-01 → 2025-12-31
Output dir  : d:\dev\tcc-mba\src\dataset\scraper\20260408\infomoney

## Batch Collection Execution
Iterates over terms, collects data, and saves to CSV in the results folder.

In [ ]:
from src.scraper import scrape_terms_parallel

# Parallel scraping: each term runs in its own thread.
# max_workers=5 is safe for InfoMoney (robust server, 0.1s sleep between pages).
saved = scrape_terms_parallel(
    terms=SEARCH_TERMS,
    start_date=START_DATE,
    end_date=END_DATE,
    output_dir=OUTPUT_DIR,
    source_name="infomoney",
    sleep_seconds=0.1,
    max_workers=5,
)
print(f"\nInfoMoney: {len(saved)} term files saved to {OUTPUT_DIR}")

## Consolidate Results
Reads all CSV files from the results folder, combines them into a single dataset, and removes duplicates (based on link).

In [4]:
# --- 1. Collection Execution (if needed) ---
# Uncomment lines below to collect new data from the API
# for term in SEARCH_TERMS:
#    df = get_news_from_period(term, START_DATE, END_DATE)

# --- 2. Consolidation and Filtering ---
print("=" * 50)
print("Starting InfoMoney Consolidation and Filtering...")
print("=" * 50)

KEYWORDS = [
    "Ibovespa", "BOVA11", "Bolsa", "Ações", "Mercado", "Câmbio", "Dólar", "Juros", "Selic", "Inflação",
    "IPCA", "Banco Central", "Copom", "Fazenda", "CDI", "Petrobras", "Vale", "Itaú", "Bradesco", "Banco do Brasil",
    "B3", "Ambev", "Eletrobras", "WEG", "Suzano", "Gerdau", "Localiza", "Rumo", "Equatorial", "BTG Pactual", "Economia"
]

all_files = glob.glob(os.path.join(OUTPUT_DIR, "news_*.csv"))

if all_files:
    print(f"Found {len(all_files)} files to consolidate.")
    df_list = [pd.read_csv(f) for f in all_files]
    consolidated_df = pd.concat(df_list, ignore_index=True)
    print(f"Total rows before deduplication: {len(consolidated_df)}")

    consolidated_df = consolidated_df.drop_duplicates(subset=["link"])
    unique_rows = len(consolidated_df)
    print(f"Total unique after deduplication: {unique_rows}")

    pattern = "|".join([fr"\b{k}\b" for k in KEYWORDS])
    mask = consolidated_df["title"].astype(str).str.contains(pattern, case=False, na=False)
    filtered_df = consolidated_df[mask].copy()
    print(f"Total after keyword filter: {len(filtered_df)}")

    if "date" in filtered_df.columns:
        filtered_df = filtered_df.sort_values(by="date", ascending=False)

    # Save one level up from infomoney/ -> scraper/YYYYMMDD/
    run_dir = os.path.dirname(OUTPUT_DIR)
    info_consolidated_path = os.path.join(run_dir, "consolidated_infomoney.csv")
    filtered_df.to_csv(info_consolidated_path, index=False)
    print(f"[SUCCESS] Saved to: {info_consolidated_path}")
    display(filtered_df.head())
else:
    print("No CSV files found. Run the scraping cell first.")

==================================================
Starting InfoMoney Consolidation and Filtering...
==================================================
Found 32 files to consolidate.
Total rows before deduplication: 84803
Total unique after deduplication: 24902
Total after keyword filter: 7541
[SUCCESS] Saved to: ..\src\dataset\scraper\20260408\consolidated_infomoney.csv

,date,title,link,source
18630,2025-12-30 19:14:13,"Ouro fecha ano com alta de 65,24%; Ibovespa é ...",https://www.infomoney.com.br/mercados/ouro-fec...,infomoney
230,2025-12-30 19:03:37,O que fez o Ibovespa subir mais de 30% em reai...,https://www.infomoney.com.br/mercados/ibovespa...,infomoney
232,2025-12-30 18:53:07,Ibovespa encerra ano em alta e sobe 34% em 202...,https://www.infomoney.com.br/mercados/ibovespa...,infomoney
233,2025-12-30 18:39:39,4 ações saltam mais de 100% em 2025: confira o...,https://www.infomoney.com.br/mercados/4-acoes-...,infomoney
234,2025-12-30 18:39:32,5 ações caem mais de 30% em 2025; confira os d...,https://www.infomoney.com.br/mercados/5-acoes-...,infomoney

## MoneyTimes Scraping
Collects financial news from MoneyTimes using the same WordPress REST API.
Uses  and a gentler rate limit (0.5s between requests).

In [14]:
# --- MoneyTimes configuration ---
from src.scraper import MONEYTIMES_API_URL

# Date-based folder: scraper/YYYYMMDD/moneytimes
MT_OUTPUT_DIR = os.path.join("..", "data", "scraper", RUN_DATE, "moneytimes")
os.makedirs(MT_OUTPUT_DIR, exist_ok=True)

print(f"MoneyTimes output: {os.path.abspath(MT_OUTPUT_DIR)}")
print(f"Scraping {len(SEARCH_TERMS)} terms from {START_DATE.date()} to {END_DATE.date()}")

MoneyTimes output: d:\dev\tcc-mba\src\dataset\scraper\20260408\moneytimes
Scraping 31 terms from 2025-01-01 to 2025-12-31

In [ ]:
# Parallel scraping for MoneyTimes.
# max_workers=3 and sleep_seconds=0.5 keep load gentle on the server.
saved_mt = scrape_terms_parallel(
    terms=SEARCH_TERMS,
    start_date=START_DATE,
    end_date=END_DATE,
    output_dir=MT_OUTPUT_DIR,
    base_url=MONEYTIMES_API_URL,
    source_name="moneytimes",
    sleep_seconds=0.5,
    max_workers=3,
)
print(f"\nMoneyTimes: {len(saved_mt)} term files saved to {MT_OUTPUT_DIR}")

## MoneyTimes Consolidation
Deduplicates and applies the same 30-keyword thematic filter.

In [7]:
# --- Consolidate MoneyTimes per-term CSVs ---
mt_files = glob.glob(os.path.join(MT_OUTPUT_DIR, "news_*.csv"))

if mt_files:
    print(f"Found {len(mt_files)} MoneyTimes files to consolidate.")
    df_mt_list = [pd.read_csv(f) for f in mt_files]
    df_mt = pd.concat(df_mt_list, ignore_index=True)
    print(f"Total rows before deduplication: {len(df_mt)}")

    df_mt = df_mt.drop_duplicates(subset=["link"])
    print(f"Total unique after deduplication: {len(df_mt)}")

    pattern = "|".join([fr"\b{k}\b" for k in KEYWORDS])
    mask = df_mt["title"].astype(str).str.contains(pattern, case=False, na=False)
    df_mt = df_mt[mask].copy()
    print(f"Total after keyword filter: {len(df_mt)}")

    df_mt = df_mt.sort_values(by="date", ascending=False)

    # Save one level up from moneytimes/ -> scraper/YYYYMMDD/
    run_dir = os.path.dirname(MT_OUTPUT_DIR)
    mt_consolidated_path = os.path.join(run_dir, "consolidated_moneytimes.csv")
    df_mt.to_csv(mt_consolidated_path, index=False)
    print(f"[SUCCESS] Saved to: {mt_consolidated_path}")
    display(df_mt.head())
else:
    print("No MoneyTimes CSV files found. Run the scraping cell first.")

Found 32 MoneyTimes files to consolidate.
Total rows before deduplication: 84766
Total unique after deduplication: 15877
Total after keyword filter: 6820
[SUCCESS] Saved to: ..\src\dataset\scraper\20260408\consolidated_moneytimes.csv

,date,title,link,source
205,2025-12-30 19:32:23,Petrobras (PETR4) anuncia corte no preço médio...,https://www.moneytimes.com.br/petrobras-petr4-...,moneytimes
206,2025-12-30 18:32:40,Ibovespa: Cogna (COGN3) dispara quase 240% no ...,https://www.moneytimes.com.br/ibovespa-cogna-c...,moneytimes
207,2025-12-30 18:31:54,SLC Agrícola (SLCE3) aprova aumento de capital...,https://www.moneytimes.com.br/slc-agricola-slc...,moneytimes
208,2025-12-30 18:28:16,Ibovespa salta 34% e tem melhor desempenho anu...,https://www.moneytimes.com.br/ibovespa-2025-lils/,moneytimes
210,2025-12-30 18:15:26,Ibovespa avança com dados de emprego e encerra...,https://www.moneytimes.com.br/ibovespa-30-12-2...,moneytimes

## Exame Scraping
Collects financial news from Exame using the same WordPress REST API.
Run after completing the InfoMoney and MoneyTimes sections above.

In [15]:
# --- Exame configuration ---
from src.scraper import EXAME_API_URL

# Date-based folder: scraper/YYYYMMDD/exame
EXAME_OUTPUT_DIR = os.path.join("..", "data", "scraper", RUN_DATE, "exame")
os.makedirs(EXAME_OUTPUT_DIR, exist_ok=True)

print(f"Exame output: {os.path.abspath(EXAME_OUTPUT_DIR)}")
print(f"Scraping {len(SEARCH_TERMS)} terms from {START_DATE.date()} to {END_DATE.date()}")

Exame output: d:\dev\tcc-mba\src\dataset\scraper\20260408\exame
Scraping 31 terms from 2025-01-01 to 2025-12-31

In [ ]:
# --- Scrape Exame (parallel, same terms) ---
saved_exame = scrape_terms_parallel(
    terms=SEARCH_TERMS,
    start_date=START_DATE,
    end_date=END_DATE,
    output_dir=EXAME_OUTPUT_DIR,
    base_url=EXAME_API_URL,
    source_name="exame",
    sleep_seconds=0.5,
    max_workers=3,
)
print(f"\nExame: {len(saved_exame)} term files saved to {EXAME_OUTPUT_DIR}")

In [16]:
# --- Consolidate Exame per-term CSVs ---
exame_files = glob.glob(os.path.join(EXAME_OUTPUT_DIR, "news_*.csv"))

if exame_files:
    print(f"Found {len(exame_files)} Exame files to consolidate.")
    df_exame_list = [pd.read_csv(f) for f in exame_files]
    df_exame = pd.concat(df_exame_list, ignore_index=True)
    print(f"Total rows before deduplication: {len(df_exame)}")

    df_exame = df_exame.drop_duplicates(subset=["link"])
    print(f"Total unique after deduplication: {len(df_exame)}")

    pattern = "|".join([fr"\b{k}\b" for k in KEYWORDS])
    mask = df_exame["title"].astype(str).str.contains(pattern, case=False, na=False)
    df_exame = df_exame[mask].copy()
    print(f"Total after keyword filter: {len(df_exame)}")

    df_exame = df_exame.sort_values(by="date", ascending=False)

    run_dir = os.path.dirname(EXAME_OUTPUT_DIR)
    exame_consolidated_path = os.path.join(run_dir, "consolidated_exame.csv")
    df_exame.to_csv(exame_consolidated_path, index=False)
    print(f"[SUCCESS] Saved to: {exame_consolidated_path}")
    display(df_exame.head())
else:
    print("No Exame CSV files found. Run the scraping cell first.")

Found 31 Exame files to consolidate.
Total rows before deduplication: 53339
Total unique after deduplication: 23461
Total after keyword filter: 4660
[SUCCESS] Saved to: ..\src\dataset\scraper\20260408\consolidated_exame.csv

,date,title,link,source
188,2025-12-30 19:15:27,De Cogna a Raízen: as maiores altas e baixas d...,https://exame.com/invest/mercados/de-cogna-a-r...,exame
189,2025-12-30 18:30:49,Ibovespa sobe 34% em 2025 e tem melhor desempe...,https://exame.com/invest/mercados/ibovespa-fec...,exame
8858,2025-12-30 17:28:24,Dólar recua 11% em 2025 e encerra o ano cotado...,https://exame.com/invest/mercados/dolar-fecham...,exame
8859,2025-12-30 16:39:22,Ata do Fed condiciona novos cortes de juros à ...,https://exame.com/invest/mercados/ata-do-fed-c...,exame
196,2025-12-30 13:22:49,Quando a Bolsa fecha em 2026? Confira o calend...,https://exame.com/invest/mercados/quando-a-bol...,exame

## Cross-Source Combination
Merges InfoMoney, MoneyTimes, and Exame into a single deduplicated dataset.
Run this cell after all three sources have been consolidated.

In [17]:
# --- Combine all sources ---
# Uses RUN_DATE set in cell 3. Add Exame if its consolidated file exists.

run_dir   = os.path.join("..", "data", "scraper", RUN_DATE)
info_path = os.path.join(run_dir, "consolidated_infomoney.csv")
mt_path   = os.path.join(run_dir, "consolidated_moneytimes.csv")

if not os.path.exists(info_path):
    raise FileNotFoundError(f"InfoMoney consolidated not found: {info_path}")
if not os.path.exists(mt_path):
    raise FileNotFoundError(f"MoneyTimes consolidated not found: {mt_path}")

df_info = pd.read_csv(info_path)
if "source" not in df_info.columns:
    df_info["source"] = "infomoney"

df_mt_final = pd.read_csv(mt_path)

sources = [df_info, df_mt_final]

# Include Exame if already consolidated
exame_path = os.path.join(run_dir, "consolidated_exame.csv")
if os.path.exists(exame_path):
    df_exame = pd.read_csv(exame_path)
    sources.append(df_exame)
    print(f"Exame      : {len(df_exame)} headlines")
else:
    print("Exame: not yet scraped (run Exame cells below to include)")

print(f"InfoMoney  : {len(df_info)} headlines")
print(f"MoneyTimes : {len(df_mt_final)} headlines")

# Combine and cross-source dedup by URL only
df_combined = pd.concat(sources, ignore_index=True)
df_combined = df_combined.drop_duplicates(subset=["link"])
df_combined = df_combined.sort_values("date", ascending=False)

combined_path = os.path.join(run_dir, "combined_news.csv")
df_combined.to_csv(combined_path, index=False)

print()
print(f"[SUCCESS] Combined dataset saved to: {combined_path}")
print(f"  Total: {len(df_combined)} headlines")
print()
print("Source distribution:")
print(df_combined["source"].value_counts())

Exame      : 4660 headlines
InfoMoney  : 7541 headlines
MoneyTimes : 6820 headlines

[SUCCESS] Combined dataset saved to: ..\src\dataset\scraper\20260408\combined_news.csv
  Total: 19021 headlines

Source distribution:
source
infomoney     7541
moneytimes    6820
exame         4660
Name: count, dtype: int64